sudo: required
language: node_js
services:
   - docker

before_install:
   - docker build -t kamalarora/docker-react -f Dockerfile.dev .

script:
   - docker run kamalarora/docker-react npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-481994741797"
  bucket_path: "docker-react"
  on:
    branch: master
